---
title: "Shana Inital Data Exploration"
author: "Shana Shapiro"
date: "4/4/2022"
output: pdf_document
---

```{r Libraries }
library(tidyverse, quietly = TRUE)
library(lubridate)
library(agricolae)
library(ggplot2)
library(zoo)
library(trend)
library(readr)
library(dplyr)
library(tidyr)
```


```{r url}
#the_url <- 'https://databank.worldbank.org/source/country-climate-and-development-report-(ccdr)'
#download for Japan
```

```{r theme}
mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "right")

theme_set(mytheme)
```


```{r explore}
GEM_raw <- read.csv('../Data/Raw/GEM_2018.csv', stringsAsFactors = TRUE)

GFD <- read.csv('../Data/Processed/GFD_processed.csv', stringsAsFactors = TRUE)
Forest <- read.csv('../Data/Processed/Forest_Share_2018_processed.csv', stringsAsFactors = TRUE)

str(GEM_raw)
dim(GEM_raw)
length(GEM_raw)
summary(GEM_raw)
```

```{r wrangle}
GEM_wrangle <- GEM_raw[1:35,]
  
colnames(GEM_wrangle) <- c("Country","Country.Code","Series","Series.Code","2018")

GEM_spread <- pivot_wider(GEM_wrangle, names_from = "Series", values_from = "2018")

GEM_renamed <- rename(GEM_spread, 
                      Exports = "Exports Merchandise, Customs, constant US$, millions, not seas. adj.", 
                      GDP = "GDP,constant 2010 LCU,millions,seas. adj.,",
                      Imports = "Imports Merchandise, Customs, constant US$, millions, not seas. adj.",
                      Production = "Industrial Production, constant US$, seas. adj.,,",
                      Stock= "Stock Markets, US$,,,", 
                      Reserves ="Total Reserves,,,,", 
                      Unemployment = "Unemployment rate,Percent,,,")

ex_df <- GEM_renamed %>%
  select(Country, Exports) %>%
  na.omit()
gdp_df <- GEM_renamed %>%
  select(Country, GDP) %>%
  na.omit()
imp_df <- GEM_renamed %>%
  select(Country, Imports) %>%
  na.omit()
pro_df <- GEM_renamed %>%
  select(Country, Production) %>%
  na.omit()
st_df <- GEM_renamed %>%
  select(Country, Stock) %>%
  na.omit()
re_df <- GEM_renamed %>%
  select(Country, Reserves) %>%
  na.omit()
un_df <- GEM_renamed %>%
  select(Country, Unemployment) %>%
  na.omit()

#put all data frames into list
df_list <- list(ex_df,gdp_df,pro_df,imp_df,st_df,re_df,un_df)

#merge all data frames in list
GEM_processed <- df_list %>% reduce(full_join, by='Country')

GEM_metadata <- colnames(GEM_raw)


GEM_processed$Exports <- as.numeric(as.character(GEM_processed$Exports))
GEM_processed$GDP <- as.numeric(as.character(GEM_processed$GDP))
GEM_processed$Imports <- as.numeric(as.character(GEM_processed$Imports))
GEM_processed$Production <- as.numeric(as.character(GEM_processed$Production))
GEM_processed$Stock <- as.numeric(as.character(GEM_processed$Stock))
GEM_processed$Reserves <- as.numeric(as.character(GEM_processed$Reserves))
GEM_processed$Unemployment <- as.numeric(as.character(GEM_processed$Unemployment))

```

```{r}
write.csv(GEM_processed,"../Data/Processed/GEM_processed_NA.csv")
write.csv(GEM_metadata,"../Data/Processed/GEM_series_metadata.csv")
```

```{r}
# plot1 <-
#   ggplot(GEM_processed, aes(x = Year, y = Exports)) +
#   geom_point() +
#   geom_smooth(method = lm, se = FALSE, col = "red") +
#   labs(x = "Year", y = "Exports")
# plot1

```

```{r}
# plot2 <-
#   ggplot(GEM_processed, aes(x = Year, y = Unemployment)) +
#   geom_point() +
#   geom_smooth(method = lm, se = FALSE, col = "blue") +
#   labs(x = "Year", y = "Unemployment")
# plot2
```
