---
title: "Presentation"
author: "Ben Culberson"
date: "4/10/2022"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

## Set up

```{r Libraries }
library(tidyverse)
library(lubridate)
library(agricolae)
library(ggplot2)
library(zoo)
library(trend)
library(readxl)
library(dplyr)
library(ggrepel)

mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "right")

theme_set(mytheme)
```

```{r clean}
GFD.df <- read.csv("../Data/Processed/GFD_processed.csv", stringsAsFactors = TRUE)
GEM.df <- read.csv("../Data/Processed/GEM_processed.csv", stringsAsFactors = TRUE)
CCDR.df <- read.csv("../Data/Processed/Forest_Share_2018_processed.csv", stringsAsFactors = TRUE)

finance_forests.df <- left_join(GFD.df, CCDR.df)
finance_forests.df <-left_join(finance_forests.df, GEM.df)

```

```{r writecsv}
#write.csv(finance_forests.df, file = "../Data/Processed/finance_forests.csv", row.names=FALSE)
```

## Exploration

```{r}
ggplot(finance_forests.df, aes(x = credit.to.private, y = Share.of.Surface.Occupied.by.Forest)) + 
  geom_point() +
  geom_label_repel(aes(label = Country),
                  box.padding   = 4, 
                  point.padding = 0.5,
                  segment.color = 'grey50')+
  geom_smooth(method = 'lm', se = FALSE, color = "darkgreen") +
  labs(x = "Domestic Credit Provided by Private Sector (%)", y = "Forest Coverage (%)", title = "Forest Coverage to Private Credit Percentage")
```
```{r}
ggplot(finance_forests.df, aes(x = assets.to.gdp, y = Share.of.Surface.Occupied.by.Forest, label=Country)) + 
  geom_point() +
  geom_label_repel(aes(label = Country),
                  box.padding   = 3.5, 
                  point.padding = 0.5,
                  segment.color = 'grey50')+
  geom_smooth(method = 'lm', se = FALSE, color = "darkblue") +
  labs(x = "Ratio of Central Bank Assets to GDP (%)", y = "Forest Coverage (%)", title = "Forest Coverage to Central Asset Percentage")
```
```{r}
#plot exports 

ggplot(finance_forests.df, aes(x = Exports, y = Share.of.Surface.Occupied.by.Forest, label=Country)) + 
  geom_point() +
  geom_label_repel(aes(label = Country),
                  box.padding   = 3.5, 
                  point.padding = 0.5,
                  segment.color = 'grey50')+
  geom_smooth(method = 'lm', se = FALSE, color = "darkred") +
  labs(x= 'Exports Merchandise (Million US$)', y = "Forest Coverage (%)", title = "Forest Coverage to Exports")
```
```{r}
#plot imports 

ggplot(finance_forests.df, aes(x = Imports, y = Share.of.Surface.Occupied.by.Forest, label=Country)) + 
  geom_point() +
  geom_label_repel(aes(label = Country),
                  box.padding   = 3.5, 
                  point.padding = 0.5,
                  segment.color = 'grey50')+
  geom_smooth(method = 'lm', se = FALSE, color = "darkorange") +
  labs(x= 'Imports Merchandise (Million US$)', y = "Forest Coverage (%)", title = "Forest Coverage to Imports")
```
```{r}
#plot reserves 

ggplot(finance_forests.df, aes(x = Reserves , y = Share.of.Surface.Occupied.by.Forest, label=Country)) + 
  geom_point() +
  geom_label_repel(aes(label = Country),
                  box.padding   = 3.5, 
                  point.padding = 0.5,
                  segment.color = 'grey50')+
  geom_smooth(method = 'lm', se = FALSE, color = "darkgreen") +
  labs(x= 'Total Reserves (US$)', y = "Forest Coverage (%)", title = "Forest Coverage to Total Reserves")
```
```{r}
#plot Unemployment 

ggplot(finance_forests.df, aes(x = Unemployment , y = Share.of.Surface.Occupied.by.Forest, label=Country)) + 
  geom_point() +
  geom_label_repel(aes(label = Country),
                  box.padding   = 3.5, 
                  point.padding = 0.5,
                  segment.color = 'grey50')+
  geom_smooth(method = 'lm', se = FALSE, color = "darkred") +
  labs(x= 'Unemployment (%)', y = "Forest Coverage (%)", title = "Forest Coverage to Percent Unemployment")
```


```{r linear.regression}
forest.regression <- lm(data = finance_forests.df, Share.of.Surface.Occupied.by.Forest ~ credit.to.private)
summary(forest.regression)

```

```{r forest.model}
Forestfinance.AIC <- lm(data = finance_forests.df, Share.of.Surface.Occupied.by.Forest ~ credit.to.private + assets.to.gdp + Reserves)
 step(Forestfinance.AIC)
 summary(Forestfinance.AIC)

Forestfinance.MR <- lm(data = finance_forests.df, Share.of.Surface.Occupied.by.Forest ~ credit.to.private + assets.to.gdp + Reserves)
summary(Forestfinance.MR)

```

```{r}
Forestfinance.anova <- aov(data = finance_forests.df, Share.of.Surface.Occupied.by.Forest ~ credit.to.private)
summary(Forestfinance.anova)
```

```{r scatterplot.2}
ggplot(finance_forests.df, aes(x = credit.to.private, y = Share.of.Surface.Occupied.by.Forest, color = Country)) + 
  geom_point(alpha = 0.5) +
  ylim(0, 35) +
  geom_smooth(method = 'lm', se = FALSE, aes(color = Country)) +
  labs(x= 'Credit to Private', y = "Forest Coverage (%)", title = "Credit to Private to Total Reserves")

```

NOTE FOR ALL: No idea what Tukey test would look like here
